apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-simulator
spec:
  selector:
    app: fleetman-position-simulator
  ports:
  - protocol: TCP
    port: 30030
    targetPort: 8080
  loadBalancerIP: 192.168.1.148
