apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: fleetman-mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: LoadBalancer
  loadBalancerIP: 192.168.1.148  