apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: fleetman-queue
  ports:
  - name: http
    protocol: TCP
    port: 8161
    targetPort: 8161
  - name: amqp
    protocol: TCP
    port: 61616
    targetPort: 61616
  type: LoadBalancer
  loadBalancerIP: 192.168.1.148  