apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: fleetman-queue
  ports:
  - name: port1
    protocol: TCP
    port: 8161
    targetPort: 8161
  - name: port2
    protocol: TCP
    port: 61616
    targetPort: 61616
