apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
  selector:
    app: fleetman-api-gateway
  ports:
  - protocol: TCP
    port: 30020
    targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: 192.168.1.148  