apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  selector:
    app: fleetman-position-tracker
  ports:
  - protocol: TCP
    port: 30010
    targetPort: 8080
  loadBalancerIP: 192.168.1.148
