apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: fleetman-webapp
  ports:
  - protocol: TCP
    port: 30080
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.1.148  