apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-api-gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-api-gateway
  template:
    metadata:
      labels:
        app: fleetman-api-gateway
    spec:
      containers:
      - name: fleetman-api-gateway
        image: supinfo4kube/api-gateway:1.0.1
        ports:
        - containerPort: 8080
        env:
        - name: SPRI_PROFILES_ACTIVE
          value: production-microservice
