apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-webapp 
  template:
    metadata:
      labels:
        app: fleetman-webapp
    spec:
      containers:
      - name: fleetman-webapp
        image: supinfo4kube/web-app:1.0.0
        ports:
        - containerPort: 80

