apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-queue
  template:
    metadata:
      labels:
        app: fleetman-queue
    spec:
      containers:
      - name: fleetman-queue
        image: supinfo4kube/queue:1.0.1
        ports:
        - containerPort: 8161
        - containerPort: 61616
